version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5003:5000"
    volumes:
      - ./backend:/app
      - ./audios:/app/audios
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
