version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5003:5000"
    volumes:
      - ./backend:/app
      - ./audios:/app/audios
    environment:
      - FLASK_ENV=development
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    restart: unless-stopped
